server:
  port: 8888
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
   prefer-ip-address: true
   
spring:
 application:
    name: Hcl-Gateway
 cloud:
  gateway:
   routes:
       - id: hungerbox
         uri: lb://HUNGERBOX-SERVICE 	
         predicates:
         - Path=/hungerbox/**
       - id: bankapp2
         uri: lb://BANKAPP-SERVICE	 
         predicates: 
         - Path=/bankapp2/**
       - id: orderservice
         uri: lb://ORDER-SERVICE
         predicates:
         - Path=/orderservice/**
       
         